### ISSUE TITLE
PHP notice: "fgetcsv(): escape must be a single character"

### ISSUE THREAD

**Issue by rwetzlmayr** [SocialEngine/phpv4-issues#247]
Steps to reproduce:
1. Go to **Settings > Performance & Caching** (http://example.com/admin/core/settings/performance).
2. Check "Translation Performance".
3. Hit "Save Changes".
4. Go to **Stats > Log Browser** and browse the error log (http://example.com/admin/log?file=main&length=50).
5. Find multiple PHP notices about a wrong parameter applied to `fgetcsv()`: 

```
2015-08-13T09:21:22+00:00 NOTICE (5): [8] fgetcsv() [function.fgetcsv]: escape must be a single character ([...]application/modules/Core/Controller/Action/Admin.php) [141]
Error Code: 63af92
Stack trace:
[...]application/modules/Core/Controller/Action/Admin.php(141): fgetcsv(Resource id #373, 0, ';', '"', '\#')
```

I'd suggest to replace line 141 of `application/modules/Core/Controller/Action/Admin.php` with 

`
          while( ( $phrase = fgetcsv( $data, 0, ';', '"', '\\' ) ) !== FALSE ) {
`

**Comment by Anshuse** [comment]
Hi @rwetzlmayr , 

Thanks for bringing this is our notice! We've reported this error log in our in our internal bug tracker to work on this in near future release. Thanks!

**Comment by smazurov** [comment]
Fixed in [4.8.10](http://blog.socialengine.com/2016/01/20/socialengine-php-4-8-10-is-released/)

**Comment by sgreiner** [comment]
This issue is still not fixed. I downloaded the 4.8.11 release and checked it.

**Comment by sgreiner** [comment]
Please see my patch in https://github.com/SocialEngine/phpv4-issues/issues/140 
It should also fix this.

**Comment by Khushboo016** [comment]
Hi @sgreiner , We have forwarded your patch for fixing the issue to our development team for internal team discussion.

Thanks!

**Comment by DonnaScriptTechs** [comment]
This is fixed for our 4.9.3 version once we release it.
