### ISSUE TITLE
Page failed validation check in SE Admin Layout Editor

### ISSUE THREAD

**Issue by Hostiso** [SocialEngine/phpv4-issues#382]
It look like when there is bad widget it will show SE error when you try to access page (this can be any page) in SE Layout Editor and only way to fix this for clients is to comment this part of code, after that you can access and edit page: 

if( $error ) {
      throw new Exception('page failed validation check');
 }

in this file: /application/modules/Core/controllers/AdminContentController.php

Please consider to change this, because clients without knowledge will not know how to bypass this error.

**Comment by Anshuse** [comment]
Hi @Hostiso, we're not sure what exactly you mean by "bad widget". When any widget is placed on a specific page, it is not meant for, then that widget will not render on that page.

As far as above code is concerned, this error message should be displayed only when there're some database discrepancies. Also, commenting out the above code will not resolve this issue but rather, it will only hide the error. So, It would be great if you can let us know the exact steps to reproduce this issue at our end so, that we can reach out to the cause of this issue, instead of just commenting out above code and hiding the error.

Thanks,

**Comment by Hostiso** [comment]
Hi @Anshuse we this is on random cases with diffrent clients, we can not really tell how to reproduce exactly, in this case our client did have larger amount of widgets on Member Profile page, some of them are disabled and he have larger amount of plugins installed.

We know disabling would not help but clients without any support would not know how to solve this, maybe have just option to show error at top of page and not completely disabling page with standard SE code as in every case when we disable that part of code page was working OK without any problems.

**Comment by Anshuse** [comment]
Hi @Hostiso , 

Previously we have faced 1-2 same cases so, I have noted down this issue in our internal bug tracker so we can find out the root-cause of this issue and can resolve it in our module.

Also, once we will be able to find out the root-cause of this issue then there'll be no need to comment out the code to hide the errors and we'll resolve the issue in our module.

Thanks,

**Comment by CLG-Brainstorm** [comment]
I'm having the same issue, triggered when creating a new page in Layout Editor using the copy existing page function, in this case creating a new page copying Album View Photo.  It's created all the database entries in engine4_core_content and ~_pages but has assigned NULL to a couple of widget's parent_content_id (should be top > middle parent id)

**Comment by Elshara** [comment]
Same here. Having the same issue when adding comet chat module then trying to place recent messages widget on any page. It pushes the errors.

**Comment by smazurov** [comment]
This has been fixed in 4.8.13

**Comment by leandrotavaresrocha** [comment]
I update my community to version 4.8.13 and this issue still happening when I try to access my layout editor. I opened a topic in the community, but seems that this problem is a bit more complicated than I expected.

**Comment by Khushboo016** [comment]
Hi @leandrotavaresrocha, We've fixed this issue in the release 4.8.13, so, you should not face the same issue after upgrading your site to 4.8.13. Also, no other client has reported this issue so far to be found in 4.8.13 core module. So, please make sure that if this issue is not taking place on your site because of a third party module or widgets belonging to that 3rd party module. You can recheck this issue after disabling the third party plugin if such a 3rd party plugin exists on your site the widgets belonging to which are placed on the page on which the issue has taken place on your site. If the issue gets resolved on disabling the 3rd party plugin, so it confirms that the issue belongs to the plugin itself and you're suggested to contact the developers of that plugin to assist you in resolving this issue. And if the issue still persists after you've disabled the 3rd party plugin, then please submit a support ticket to us for this issue at support@socialengine.com, so we can proceed to look further into this.

Thanks & Regards!
