### ISSUE TITLE
Line breaks in comments

### ISSUE THREAD

**Issue by MeisterG** [SocialEngine/phpv4-issues#40]
This has been an ongoing issue and has not been resolved, I've always wondered why.

When you type a comment as:
Line 1
Line 2

Line 3

Once you post the comment it appears as:
Line 1
Line 2
Line 3

Its a bit nitpicky but you cant see this happening on most of the other social network scripts.

**Comment by Anshuse** [comment]
Hi @MeisterG ,

Thanks for bringing this issue to our attention. We've reported this issue in our internal bug tracker and will resolve this in near future.

Best Regards,
Anshu

**Comment by myetter37** [comment]
SocialEngine PHP version 4.8.9 has been released, and this issue has been fixed in that release.

**Comment by SpiritWolfie** [comment]
I hate to be the one to post this, but the issue actually hasn't been fixed, While it now works for first post, any comments after that still do not allow line breaks. they still do this 
Test
Test

instead of 
Test

Test

Could you guys add a hot fix to include it on responses too please?
