### ISSUE TITLE
Event > Discussions: Editing post or comment displays html in post

### ISSUE THREAD

**Issue by auntialias** [SocialEngine/phpv4-issues#48]
(I'm using SE PHP Demo version name of zip file I downloaded is socialengine488_trial_53.zip)

# Steps to duplicate:
1. Create Event (or, if one is created, go to that event)
2. Click the  **Discussions** tab
3. Click Post New Topic
4. Compose Post, and click the Post New Topic button to save topic.  
Page refreshes to display post you just created
5. Click the Edit button/link
6. Edit your message. click Save
7. **RESULTS:** html tags display in the message. 

Screenshot attached. The top item was _not_ edited; the bottom two were edited.

![google chromepolarcoordinates-002](https://cloud.githubusercontent.com/assets/1919971/7844726/3fe87682-0467-11e5-88ce-b055fdf1be34.png)

**Comment by Anshuse** [comment]
Hello @auntialias , 

Thanks for bringing this issue to our attention.

We've added this issue in our internal bug tracker and will resolve this issue in near future upgrade of SocialEngine.

Best Regards,
Anshu

**Comment by myetter37** [comment]
SocialEngine PHP version 4.8.9 has been released, and this issue has been fixed in that release.

**Comment by LuciusPrime** [comment]
@myetter37 I have SocialEngine PHP version 4.8.9 and still the same issue as above. It appears a lot of stuff got glitchy in the last few versions, is this to sell more extended support?
