### ISSUE TITLE
Main Photo Profile Widget Missing in Member Home

### ISSUE THREAD

**Issue by leandrotavaresrocha** [SocialEngine/phpv4-issues#692]
(Thanks for reporting an issue! Please make sure you click the link above to view the issue guidelines, then fill out the blanks below.)

What are the steps to reproduce this issue?
-------------------------------------------
1. Upgrade your website to 4.9

What happens?
-------------
1. The widget that display the user profile image in the member home page at left of the feed doesnt appear.

What were you expecting to happen?
----------------------------------
1. The widget should appear displaying the user profile in the left of the member home page.

Any logs, error output, etc?
----------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.) 

```
Paste Log Here
```

Any other comments?
-------------------
…

What versions of software are you using?
----------------------------------------
**Operating System:** Centos OS 6

**SocialEngine PHP Version:** 4.9

**Comment by Elshara** [comment]
What widget?

**Comment by leandrotavaresrocha** [comment]
The widget that display the user profile image. This widget is by default the first widget in the left sidebar on in the member home page.

**Comment by Elshara** [comment]
Oh the profile photo. Yeah I seen that one. It's not there anymore in
4.9? I totally didn't check.

**Comment by DonnaScriptTechs** [comment]
This is working fine on all of my upgraded sites. Did you have any third party plugins? There have been issues with upgrades and third party plugins. Can you check for errors with development mode?

**Comment by DonnaScriptTechs** [comment]
Is this fixed by the patch in your other report? We can't reproduce this issue.

**Comment by leandrotavaresrocha** [comment]
@DonnaScriptTechs, still not working. I already checked and the widget is in the right place in the admincp.

The widget in question is the "Main Photo of Member"

**Comment by Elshara** [comment]
That sucks. Have you tried fresh install?

**Comment by DonnaScriptTechs** [comment]
Did you try a fresh development site to see if perhaps there is a conflict in some customizations or plugins? We can't reproduce this issue on our installs or upgrades. We will be releasing 4.9.1 soon. Perhaps that will work better for you.

**Comment by Elshara** [comment]
Lets hope the issue is fixed in the same release. Perhaps displaying
photos as inline-block might help.
